# Complete Android CI/CD Pipeline with Firebase App Distribution
# Pure GitHub Actions implementation - no Fastlane required
name: Android CI/CD

# Trigger conditions
on:
  # Automatic triggers based on branch pushes
  push:
    branches:
      - main          # Production release builds
      - develop       # Development debug builds
      - staging       # Staging debug builds
      - uat           # UAT debug builds

  # Pull request validation (build but don't distribute)
  pull_request:
    branches: [main, develop, staging, uat]

  # Manual trigger with full parameter control
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Build flavor'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - uat
          - prod
          - internal
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      distribution_groups:
        description: 'Firebase distribution groups'
        required: false
        default: 'QC,Developers'
      skip_tests:
        description: 'Skip tests'
        type: boolean
        default: false
      create_release:
        description: 'Create GitHub release'
        type: boolean
        default: false
        release_version:
          description: 'Release version (if creating release)'
          required: false
          default: '1.0.0'

jobs:
  build:
    uses: ./.github/workflows/android-build.yml
    with:
      flavor: ${{ github.event.inputs.flavor || (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/develop' && 'dev') || (github.ref == 'refs/heads/staging' && 'staging') || (github.ref == 'refs/heads/uat' && 'uat') || 'internal' }}
      build_type: ${{ github.event.inputs.build_type || (github.ref == 'refs/heads/main' && 'release') || 'debug' }}
      skip_tests: ${{ github.event.inputs.skip_tests || false }}